"use client";

import { useState, useMemo } from "react";
import ToolPageLayout from "@/components/layout/ToolPageLayout";
import CodeMirrorEditor from "@/components/ui/CodeMirrorEditor";
import { toast } from "sonner";
import {
    Server,
    Shield,
    Gauge,
    FileWarning,
    Link,
    Lock,
    ImageOff,
    RefreshCw,
    Copy,
    Download,
    Settings2,
    Globe,
    FileCode
} from "lucide-react";

interface HtaccessConfig {
    domain: string;
    https: "none" | "force";
    www: "none" | "add" | "remove";
    // Security
    disableIndex: boolean;
    blockDotFiles: boolean;
    blockHotlink: boolean;
    securityHeaders: boolean;
    // Performance
    compression: boolean;
    caching: boolean;
    // Errors
    error404: string;
}

const defaultConfig: HtaccessConfig = {
    domain: "",
    https: "force",
    www: "remove",
    disableIndex: true,
    blockDotFiles: true,
    blockHotlink: false,
    securityHeaders: true,
    compression: true,
    caching: true,
    error404: ""
};

export default function HtaccessGeneratorPage() {
    const [config, setConfig] = useState<HtaccessConfig>(defaultConfig);

    const updateConfig = (key: keyof HtaccessConfig, value: any) => {
        setConfig(prev => ({ ...prev, [key]: value }));
    };

    // --- Generation Logic ---

    const generatedCode = useMemo(() => {
        const { domain, https, www, disableIndex, blockDotFiles, blockHotlink, securityHeaders, compression, caching, error404 } = config;

        let code = `# Generated by ToolKit Pro
# ====================================
# Apache .htaccess Configuration
# ====================================

RewriteEngine On

`;

        // 1. Domain & Rewrite Rules
        if (domain) {
            const cleanDomain = domain.replace(/^(https?:\/\/)?(www\.)?/, '');

            // Force HTTPS
            if (https === "force") {
                code += `# Force HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

`;
            }

            // WWW Handling
            if (www !== "none") {
                const targetWww = www === "add" ? "www." : "";
                const condition = www === "add" ? "!^www\." : "^www\.";
                const protocol = https === "force" ? "https" : "http";

                code += `# ${www === 'add' ? 'Add' : 'Remove'} WWW
RewriteCond %{HTTP_HOST} ${condition}${cleanDomain} [NC]
RewriteRule ^(.*)$ ${protocol}://${targetWww}${cleanDomain}/$1 [R=301,L]

`;
            }
        }

        // 2. Security
        if (disableIndex) {
            code += `# Disable Directory Browsing
Options -Indexes

`;
        }

        if (blockDotFiles) {
            code += `# Block Access to Hidden Files
<FilesMatch "^\.">
    Order allow,deny
    Deny from all
</FilesMatch>

`;
        }

        if (blockHotlink && domain) {
            const cleanDomain = domain.replace(/^(https?:\/\/)?(www\.)?/, '').replace(/\./g, '\\.');
            code += `# Prevent Image Hotlinking
RewriteCond %{HTTP_REFERER} !^$ RewriteCond %{HTTP_REFERER} !^http(s)?://(www\.)?${cleanDomain} [NC]
RewriteRule \.(jpg|jpeg|png|gif)$ - [F,NC,L]

`;
        }

        if (securityHeaders) {
            code += `# Security Headers
<IfModule mod_headers.c>
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-Content-Type-Options "nosniff"
    Referrer-Policy "no-referrer-when-downgrade"
</IfModule>

`;
        }

        // 3. Performance
        if (compression) {
            code += `# Enable GZIP Compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/plain
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/xml
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/xml
    AddOutputFilterByType DEFLATE application/xhtml+xml
    AddOutputFilterByType DEFLATE application/rss+xml
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE application/x-javascript
</IfModule>

`;
        }

        if (caching) {
            code += `# Browser Caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/pdf "access plus 1 month"
    ExpiresByType text/javascript "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType image/x-icon "access plus 1 year"
    ExpiresDefault "access plus 2 days"
</IfModule>

`;
        }

        // 4. Error Pages
        if (error404) {
            code += `# Custom Error Pages
ErrorDocument 404 ${error404}
`;
        }

        return code.trim();
    }, [config]);

    // --- Handlers ---

    const copyCode = () => {
        navigator.clipboard.writeText(generatedCode);
        toast.success("Copied to clipboard!");
    };

    const downloadFile = () => {
        const blob = new Blob([generatedCode], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = ".htaccess";
        a.click();
        URL.revokeObjectURL(url);
    };

    // --- UI Slots ---

    const EditorContent = (
        <div className="h-full w-full flex flex-col bg-[var(--bg)] overflow-auto">
            <div className="bg-[var(--bg-secondary)] px-4 py-1 border-b border-[var(--border)] text-[10px] font-bold text-[var(--fg-secondary)] uppercase tracking-wider flex justify-between">
                <span>Configuration</span>
                <Server size={12} />
            </div>

            <div className="p-6 space-y-6">
                {/* 1. Domain Setup */}
                <div className="space-y-3">
                    <div className="flex items-center gap-2 text-xs font-bold text-[var(--fg-secondary)] uppercase border-b border-[var(--border)] pb-2 mb-2">
                        <Globe size={12} /> 1. Domain Setup
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-bold text-[var(--fg-secondary)]">Domain Name</label>
                        <input
                            type="text"
                            value={config.domain}
                            onChange={(e) => updateConfig("domain", e.target.value)}
                            placeholder="example.com"
                            className="w-full bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-amber-500"
                        />
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                        <div className="space-y-1">
                            <label className="text-xs font-bold text-[var(--fg-secondary)]">HTTPS</label>
                            <select
                                value={config.https}
                                onChange={(e) => updateConfig("https", e.target.value)}
                                className="w-full bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2 text-sm outline-none"
                            >
                                <option value="none">Don't Force</option>
                                <option value="force">Force HTTPS</option>
                            </select>
                        </div>
                        <div className="space-y-1">
                            <label className="text-xs font-bold text-[var(--fg-secondary)]">WWW</label>
                            <select
                                value={config.www}
                                onChange={(e) => updateConfig("www", e.target.value)}
                                className="w-full bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2 text-sm outline-none"
                            >
                                <option value="none">No Redirection</option>
                                <option value="remove">Remove WWW</option>
                                <option value="add">Add WWW</option>
                            </select>
                        </div>
                    </div>
                </div>

                {/* 2. Security */}
                <div className="space-y-3">
                    <div className="flex items-center gap-2 text-xs font-bold text-[var(--fg-secondary)] uppercase border-b border-[var(--border)] pb-2 mb-2">
                        <Shield size={12} /> 2. Security
                    </div>
                    <div className="space-y-2">
                        <Toggle label="Disable Directory Browsing" checked={config.disableIndex} onChange={(v) => updateConfig("disableIndex", v)} />
                        <Toggle label="Block Dot Files (.git, .env)" checked={config.blockDotFiles} onChange={(v) => updateConfig("blockDotFiles", v)} />
                        <Toggle label="Security Headers (X-Frame-Options)" checked={config.securityHeaders} onChange={(v) => updateConfig("securityHeaders", v)} />
                        <Toggle label="Prevent Image Hotlinking" checked={config.blockHotlink} onChange={(v) => updateConfig("blockHotlink", v)} disabled={!config.domain} />
                    </div>
                </div>

                {/* 3. Performance */}
                <div className="space-y-3">
                    <div className="flex items-center gap-2 text-xs font-bold text-[var(--fg-secondary)] uppercase border-b border-[var(--border)] pb-2 mb-2">
                        <Gauge size={12} /> 3. Performance
                    </div>
                    <div className="space-y-2">
                        <Toggle label="Enable GZIP Compression" checked={config.compression} onChange={(v) => updateConfig("compression", v)} />
                        <Toggle label="Browser Caching (Expires)" checked={config.caching} onChange={(v) => updateConfig("caching", v)} />
                    </div>
                </div>

                {/* 4. Error Pages */}
                <div className="space-y-3">
                    <div className="flex items-center gap-2 text-xs font-bold text-[var(--fg-secondary)] uppercase border-b border-[var(--border)] pb-2 mb-2">
                        <FileWarning size={12} /> 4. Error Pages
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-bold text-[var(--fg-secondary)]">Custom 404 Path</label>
                        <input
                            type="text"
                            value={config.error404}
                            onChange={(e) => updateConfig("error404", e.target.value)}
                            placeholder="/404.html"
                            className="w-full bg-[var(--bg-secondary)] border border-[var(--border)] rounded px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-amber-500"
                        />
                    </div>
                </div>
            </div>
        </div>
    );

    const PreviewContent = (
        <div className="h-full w-full flex flex-col bg-[var(--bg)] overflow-hidden">
            <div className="bg-amber-50 dark:bg-amber-900/30 px-4 py-1 border-b border-amber-200 dark:border-amber-800 text-[10px] font-bold text-amber-600 dark:text-amber-300 uppercase tracking-wider flex justify-between">
                <span>Generated .htaccess</span>
                <span>{generatedCode.split('\n').length} Lines</span>
            </div>

            <div className="flex-1 overflow-auto">
                <CodeMirrorEditor
                    language="apache" // Using 'apache' mode for syntax highlighting
                    value={generatedCode}
                    onChange={() => { }}
                />
            </div>
        </div>
    );

    const SeoContent = (
        <>
            <h2 className="text-2xl font-bold text-[var(--fg)] mb-4 border-b border-[var(--border)] pb-2">.htaccess Generator</h2>
            <div className="grid md:grid-cols-2 gap-8 mt-8">
                <div>
                    <h3 className="text-lg font-semibold text-[var(--fg)] mb-2">Apache Configuration</h3>
                    <p className="text-[var(--fg-secondary)]">Generate configuration files for Apache web servers. Handle redirects, security, and performance optimization visually.</p>
                </div>
                <div>
                    <h3 className="text-lg font-semibold text-[var(--fg)] mb-2">Best Practices</h3>
                    <p className="text-[var(--fg-secondary)]">Includes standard security headers and caching rules recommended for modern web applications.</p>
                </div>
            </div>
        </>
    );

    return (
        <ToolPageLayout
            title=".htaccess"
            filename=".htaccess"
            defaultFilename=".htaccess"
            extension="conf"
            toolId="htaccess"
            editorSlot={EditorContent}
            previewSlot={PreviewContent}
            seoContent={SeoContent}
            onCopy={copyCode}
            onDownload={downloadFile}
        />
    );
}

// --- Helper Component ---
function Toggle({ label, checked, onChange, disabled }: { label: string; checked: boolean; onChange: (val: boolean) => void; disabled?: boolean }) {
    return (
        <label className={`flex items-center justify-between cursor-pointer py-1 ${disabled ? "opacity-50 cursor-not-allowed" : ""}`}>
            <span className="text-xs font-medium text-[var(--fg)]">{label}</span>
            <div className="relative">
                <input
                    type="checkbox"
                    checked={checked}
                    onChange={(e) => !disabled && onChange(e.target.checked)}
                    className="sr-only peer"
                    disabled={disabled}
                />
                <div className="w-9 h-5 bg-[var(--border)] rounded-full peer-checked:bg-amber-600 transition-colors"></div>
                <div className="absolute left-0.5 top-0.5 w-4 h-4 bg-white rounded-full transition-transform peer-checked:translate-x-4"></div>
            </div>
        </label>
    );
}